---
abstract: 'Displays the elapsed time as a human readable string.'
author:
  - 'Burak Gursoy <burak@cpan.org>'
build_requires:
  Test::More: 0.40
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Elapsed
no_index:
  directory:
    - monolithic_version
    - builder
    - t
provides:
  Time::Elapsed:
    file: lib/Time/Elapsed.pm
    version: 0.31
  Time::Elapsed::Lang::DE:
    file: lib/Time/Elapsed/Lang/DE.pm
    version: 0.31
  Time::Elapsed::Lang::EN:
    file: lib/Time/Elapsed/Lang/EN.pm
    version: 0.31
  Time::Elapsed::Lang::TR:
    file: lib/Time/Elapsed/Lang/TR.pm
    version: 0.31
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-time-elapsed/
version: 0.31
